# pretrain: exps/k400/ViT-L/14/16f/k400-vit-l-14-f16.pt
pretrain:
resume:
seed: 1024
data:
    dataset: hmdb51
    modality: residual
    num_segments: 16
    seg_length: 1
    batch_size: 2
    workers: 4
    num_classes: 51
    image_tmpl: 'image_{:06d}.jpg'
    train_root: '/home/NAS_netmedia/Videodataset/hmdb51/mpeg4_videos'
    val_root: '/home/NAS_netmedia/Videodataset/hmdb51/mpeg4_videos'
    train_list: 'lists/hmdb51/train_rgb_split_1.txt'
    val_list: 'lists/hmdb51/val_rgb_split_1.txt'
    label_list: 'lists/hmdb51/hmdb51_labels.csv'
    input_size: 224
    random_shift: True
    output_path: /home/NAS_netmedia/gmk/BIKE/exps
    GOP_SIZE: 12
network:
    arch: ViT-L/14
    init: True 
    tm: False
    drop_out: 0.0 
    emb_dropout: 0.0 
    sim_header: Transf
    interaction: VCS
    video_prompt: False
    joint_st: False
    drop: 0      
    fix_text: True  
    fix_video: True  
    Block: Origin
    use_text_prompt_learning: False
solver:
    type: cosine
    epochs: 20
    start_epoch: 0
    optim: adamw
    lr: 5.e-5
    mv_lr_ratio: 0.1  # mv_head学习率
    lr_warmup_step: 5
    weight_decay: 0.2
    loss_type: NCE
    evaluate: False
    clip_ratio: 0.1
    grad_accumulation_steps: 1
logging:
    print_freq: 10
    eval_freq: 2